/** Self-contained HTML rendering of the semantic model (no scripts, no external assets). Also the visual source for the ZUGFeRD PDF (Task 2.7). */
import { Decimal } from "decimal.js";
import type { DetectedFormat } from "../detect/index.js";
import type { InvoiceModel } from "../model/schema.js";
import { escapeXml as esc } from "../serialize/xml.js";

type Lang = "de" | "en";

const T = {
  de: {
    invoice: "Rechnung",
    creditNote: "Gutschrift",
    number: "Nummer",
    issueDate: "Rechnungsdatum",
    dueDate: "Fällig am",
    buyerRef: "Käuferreferenz / Leitweg-ID",
    order: "Bestellung",
    contract: "Vertrag",
    period: "Leistungszeitraum",
    seller: "Verkäufer",
    buyer: "Käufer",
    vatId: "USt-IdNr.",
    taxNo: "Steuernummer",
    contact: "Kontakt",
    pos: "Pos.",
    item: "Bezeichnung",
    qty: "Menge",
    unit: "Einheit",
    price: "Einzelpreis",
    vat: "USt",
    net: "Netto",
    breakdown: "Umsatzsteuer-Aufschlüsselung",
    category: "Kategorie",
    rate: "Satz",
    taxable: "Bemessungsgrundlage",
    tax: "Steuer",
    reason: "Befreiungsgrund",
    lineTotal: "Summe Positionen",
    allowances: "Nachlässe",
    charges: "Zuschläge",
    taxExcl: "Gesamt netto",
    taxAmount: "Umsatzsteuer",
    taxIncl: "Gesamt brutto",
    paid: "Bereits gezahlt",
    rounding: "Rundung",
    payable: "Zahlbetrag",
    payment: "Zahlung",
    means: "Zahlungsart",
    iban: "IBAN",
    bic: "BIC",
    holder: "Kontoinhaber",
    remittance: "Verwendungszweck",
    terms: "Zahlungsbedingungen",
    notes: "Hinweise",
    generated:
      "Vorschau erzeugt von Kontor MCP aus dem EN-16931-Datenmodell – keine steuerliche oder rechtliche Beratung.",
    format: "Format",
    delivery: "Lieferung",
    deliveryDate: "Lieferdatum",
  },
  en: {
    invoice: "Invoice",
    creditNote: "Credit note",
    number: "Number",
    issueDate: "Issue date",
    dueDate: "Due date",
    buyerRef: "Buyer reference / Leitweg-ID",
    order: "Order",
    contract: "Contract",
    period: "Invoicing period",
    seller: "Seller",
    buyer: "Buyer",
    vatId: "VAT ID",
    taxNo: "Tax number",
    contact: "Contact",
    pos: "No.",
    item: "Item",
    qty: "Quantity",
    unit: "Unit",
    price: "Unit price",
    vat: "VAT",
    net: "Net",
    breakdown: "VAT breakdown",
    category: "Category",
    rate: "Rate",
    taxable: "Taxable amount",
    tax: "Tax",
    reason: "Exemption reason",
    lineTotal: "Sum of lines",
    allowances: "Allowances",
    charges: "Charges",
    taxExcl: "Total net",
    taxAmount: "VAT",
    taxIncl: "Total gross",
    paid: "Prepaid",
    rounding: "Rounding",
    payable: "Amount due",
    payment: "Payment",
    means: "Payment means",
    iban: "IBAN",
    bic: "BIC",
    holder: "Account holder",
    remittance: "Remittance information",
    terms: "Payment terms",
    notes: "Notes",
    generated:
      "Preview generated by Kontor MCP from the EN 16931 semantic model – not tax or legal advice.",
    format: "Format",
    delivery: "Delivery",
    deliveryDate: "Delivery date",
  },
} as const;

/** Display formatting only: fixed 2 decimals via decimal.js, then locale separators by string ops (no float math). */
export function formatAmount(v: string | undefined, lang: Lang, decimals = 2): string {
  if (v === undefined || v === "") return "";
  let d: Decimal;
  try {
    d = new Decimal(v);
  } catch {
    return esc(v);
  }
  const fixed = decimals >= 0 ? d.toFixed(decimals) : d.toString();
  const [int = "0", frac] = fixed.replace("-", "").split(".");
  const grouped = int.replace(/\B(?=(\d{3})+(?!\d))/g, lang === "de" ? "." : ",");
  const sep = lang === "de" ? "," : ".";
  return `${d.isNegative() ? "-" : ""}${grouped}${frac !== undefined ? sep + frac : ""}`;
}

const CSS = `
:root{--ink:#1a1a1a;--muted:#5f6368;--line:#d9dcе0;--accent:#0b57d0;--bg:#fff}
*{box-sizing:border-box}body{margin:0;background:#f3f4f6;color:var(--ink);font:14px/1.45 -apple-system,"Segoe UI",Roboto,Helvetica,Arial,sans-serif}
.page{max-width:900px;margin:24px auto;background:var(--bg);padding:40px 48px;border:1px solid #e5e7eb}
h1{font-size:26px;margin:0 0 4px}.sub{color:var(--muted);margin-bottom:24px}
.grid{display:grid;grid-template-columns:1fr 1fr;gap:24px;margin:16px 0}
.card h2{font-size:12px;text-transform:uppercase;letter-spacing:.06em;color:var(--muted);margin:0 0 6px}
dl{margin:0;display:grid;grid-template-columns:max-content 1fr;gap:2px 12px}dt{color:var(--muted)}dd{margin:0}
table{width:100%;border-collapse:collapse;margin:16px 0}th,td{padding:8px 6px;border-bottom:1px solid #e5e7eb;vertical-align:top}
th{text-align:left;font-size:12px;color:var(--muted);text-transform:uppercase;letter-spacing:.04em}
td.num,th.num{text-align:right;white-space:nowrap;font-variant-numeric:tabular-nums}
.totals{margin-left:auto;width:340px}.totals td{border:0;padding:4px 6px}.totals tr.grand td{border-top:2px solid var(--ink);font-weight:700;font-size:16px}
.note{white-space:pre-wrap}.foot{margin-top:32px;font-size:11px;color:var(--muted)}
@media print{body{background:#fff}.page{border:0;margin:0;max-width:none}}
`.replace("е0", "e0");

export function renderHtmlPreview(
  m: InvoiceModel,
  opts: { lang: Lang; format?: DetectedFormat },
): string {
  const L = opts.lang;
  const t = T[L];
  const amt = (v: string | undefined) => formatAmount(v, L);
  const qty = (v: string) => formatAmount(v, L, -1);
  const title = ["381", "396", "261", "262", "308"].includes(m.typeCode) ? t.creditNote : t.invoice;
  const row = (k: string, v: string | undefined) =>
    v ? `<dt>${esc(k)}</dt><dd>${esc(v)}</dd>` : "";
  const addr = (a: InvoiceModel["seller"]["postalAddress"]) =>
    a
      ? [
          a.line1,
          a.line2,
          a.line3,
          [a.postCode, a.city].filter(Boolean).join(" "),
          a.countrySubdivision,
          a.countryCode,
        ]
          .filter(Boolean)
          .map((x) => esc(String(x)))
          .join("<br>")
      : "";
  const party = (label: string, p: InvoiceModel["seller"] | InvoiceModel["buyer"], extra = "") => `
<div class="card"><h2>${esc(label)}</h2>
<div><strong>${esc(p.name)}</strong>${p.tradingName && p.tradingName !== p.name ? `<br><span class="muted">${esc(p.tradingName)}</span>` : ""}</div>
<div>${addr(p.postalAddress)}</div>
<dl>${row(t.vatId, p.vatId)}${extra}${p.contact ? row(t.contact, [p.contact.name, p.contact.phone, p.contact.email].filter(Boolean).join(" · ")) : ""}${p.electronicAddress ? row("E-Mail/ID", p.electronicAddress.value) : ""}</dl></div>`;

  const lines = m.lines
    .map(
      (l) =>
        `<tr><td>${esc(l.id)}</td><td>${esc(l.item.name)}${l.item.description ? `<br><span class="muted">${esc(l.item.description)}</span>` : ""}${l.note ? `<br><span class="muted note">${esc(l.note)}</span>` : ""}${l.period ? `<br><span class="muted">${esc(t.period)}: ${esc(l.period.start ?? "")} – ${esc(l.period.end ?? "")}</span>` : ""}</td><td class="num">${qty(l.quantity)}</td><td>${esc(l.quantityUnitCode)}</td><td class="num">${amt(l.price.netPrice)}${l.price.baseQuantity ? ` / ${qty(l.price.baseQuantity)}` : ""}</td><td class="num">${esc(l.vat.categoryCode)} ${l.vat.rate ? `${formatAmount(l.vat.rate, L, -1)} %` : ""}</td><td class="num">${amt(l.netAmount)}</td></tr>`,
    )
    .join("\n");

  const breakdown = m.vatBreakdown
    .map(
      (b) =>
        `<tr><td>${esc(b.categoryCode)}</td><td class="num">${b.rate ? `${formatAmount(b.rate, L, -1)} %` : "–"}</td><td class="num">${amt(b.taxableAmount)}</td><td class="num">${amt(b.taxAmount)}</td><td>${esc([b.exemptionReasonCode, b.exemptionReason].filter(Boolean).join(" – "))}</td></tr>`,
    )
    .join("\n");

  const tot = m.totals;
  const totRow = (k: string, v: string | undefined, cls = "") =>
    v !== undefined
      ? `<tr class="${cls}"><td>${esc(k)}</td><td class="num">${amt(v)} ${esc(m.currency)}</td></tr>`
      : "";
  const p = m.paymentInstructions;
  const payment = p
    ? `<div class="card"><h2>${esc(t.payment)}</h2><dl>${row(t.means, [p.meansTypeCode, p.meansText].filter(Boolean).join(" – "))}${(p.creditTransfers ?? []).map((c) => row(t.iban, c.account) + row(t.bic, c.bic) + row(t.holder, c.accountName)).join("")}${row(t.remittance, p.remittanceInfo)}${row(t.terms, m.paymentTerms)}${row(t.dueDate, m.dueDate)}</dl></div>`
    : m.paymentTerms || m.dueDate
      ? `<div class="card"><h2>${esc(t.payment)}</h2><dl>${row(t.terms, m.paymentTerms)}${row(t.dueDate, m.dueDate)}</dl></div>`
      : "";
  const notes = m.notes?.length
    ? `<div class="card"><h2>${esc(t.notes)}</h2>${m.notes.map((n) => `<p class="note">${n.subjectCode ? `<span class="muted">[${esc(n.subjectCode)}]</span> ` : ""}${esc(n.note)}</p>`).join("")}</div>`
    : "";
  const fmt = opts.format
    ? [
        opts.format.syntax?.toUpperCase(),
        opts.format.cius === "xrechnung" ? `XRechnung ${opts.format.version ?? ""}` : undefined,
        opts.format.profile ? `Factur-X/ZUGFeRD ${opts.format.profile.toUpperCase()}` : undefined,
      ]
        .filter(Boolean)
        .join(" · ")
    : "";
  const del = m.delivery;
  const delivery = del
    ? `<div class="card"><h2>${esc(t.delivery)}</h2><div>${esc(del.deliverToName ?? "")}</div><div>${addr(del.address)}</div><dl>${row(t.deliveryDate, del.actualDeliveryDate)}</dl></div>`
    : "";

  return `<!DOCTYPE html>
<html lang="${L}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} ${esc(m.number)}</title><style>${CSS}</style></head>
<body><div class="page">
<h1>${esc(title)} ${esc(m.number)}</h1>
<div class="sub">${esc(t.issueDate)}: ${esc(m.issueDate)}${m.dueDate ? ` · ${esc(t.dueDate)}: ${esc(m.dueDate)}` : ""}${fmt ? ` · ${esc(t.format)}: ${esc(fmt)}` : ""}</div>
<div class="grid">
${party(t.seller, m.seller, row(t.taxNo, m.seller.taxRegistrationId) + (m.seller.legalRegistrationId ? row("Reg.", m.seller.legalRegistrationId.value) : ""))}
${party(t.buyer, m.buyer, m.buyer.identifier ? row("ID", m.buyer.identifier.value) : "")}
</div>
<dl>${row(t.buyerRef, m.buyerReference)}${row(t.order, m.purchaseOrderReference)}${row(t.contract, m.contractReference)}${m.invoicePeriod ? row(t.period, `${m.invoicePeriod.start ?? ""} – ${m.invoicePeriod.end ?? ""}`) : ""}</dl>
<table><thead><tr><th>${esc(t.pos)}</th><th>${esc(t.item)}</th><th class="num">${esc(t.qty)}</th><th>${esc(t.unit)}</th><th class="num">${esc(t.price)}</th><th class="num">${esc(t.vat)}</th><th class="num">${esc(t.net)} ${esc(m.currency)}</th></tr></thead>
<tbody>
${lines}
</tbody></table>
<table class="totals"><tbody>
${totRow(t.lineTotal, tot.lineExtension)}${totRow(t.allowances, tot.allowanceTotal)}${totRow(t.charges, tot.chargeTotal)}${totRow(t.taxExcl, tot.taxExclusive)}${totRow(t.taxAmount, tot.taxAmount)}${totRow(t.taxIncl, tot.taxInclusive)}${totRow(t.paid, tot.paid)}${totRow(t.rounding, tot.rounding)}${totRow(t.payable, tot.payable, "grand")}
</tbody></table>
<h2 style="font-size:12px;text-transform:uppercase;color:#5f6368">${esc(t.breakdown)} (BG-23)</h2>
<table><thead><tr><th>${esc(t.category)}</th><th class="num">${esc(t.rate)}</th><th class="num">${esc(t.taxable)}</th><th class="num">${esc(t.tax)}</th><th>${esc(t.reason)}</th></tr></thead><tbody>
${breakdown}
</tbody></table>
<div class="grid">${payment}${delivery}</div>
${notes}
<div class="foot">${esc(t.generated)}</div>
</div></body></html>
`;
}
