/**
 * Generates docs/BT-COVERAGE.md from the model's BT map (Task 1.3 AC: ≥ 90 % of EN 16931 core BTs).
 * Usage: pnpm bt-coverage
 */
import { writeFileSync } from "node:fs";
import { ALL_BT_IDS, BT_MAP } from "../packages/core/src/model/bt-map.js";

const covered = new Map<string, string>();
for (const [path, code] of Object.entries(BT_MAP))
  if (code.startsWith("BT-")) covered.set(code, path);
const missing = ALL_BT_IDS.filter((b) => !covered.has(b));
const pct = ((covered.size / ALL_BT_IDS.length) * 100).toFixed(1);

const rows = ALL_BT_IDS.map(
  (b) => `| ${b} | ${covered.get(b) ?? "—"} | ${covered.has(b) ? "✅" : "❌"} |`,
).join("\n");
const groups = Object.entries(BT_MAP)
  .filter(([, c]) => c.startsWith("BG-"))
  .sort((a, b) => Number(a[1].slice(3)) - Number(b[1].slice(3)))
  .map(([p, c]) => `| ${c} | \`${p}\` |`)
  .join("\n");

const md = `# EN 16931 business-term coverage of \`InvoiceModel\`

Generated by \`pnpm bt-coverage\` from \`packages/core/src/model/bt-map.ts\` — do not edit by hand.

**Coverage: ${covered.size} / ${ALL_BT_IDS.length} core BTs (${pct} %)**${missing.length ? ` — missing: ${missing.join(", ")}` : " — complete."}

Note: BT-4 does not exist in the published EN 16931-1 model; BT-162…BT-165 are the address line 3 terms added in amendment A1.

## Groups

| BG | model path |
|---|---|
${groups}

## Business terms

| BT | model path | covered |
|---|---|---|
${rows}

## Twin fringe (Task 1.3 acceptance test)

\`packages/core/test/parse.test.ts\` parses every UBL/CII twin pair of the official XRechnung test suite and requires deep-equal models after normalising:

1. **Numeric formatting** — the same value written as \`19\` vs \`19.00\` (strings are kept verbatim in the model; the test compares numerically).
2. **Explicit zero vs omitted** for the optional totals BT-107/108/113/114.
3. **Source-data differences between twins** (verified by hand in the XML, not mapping errors): 01.02a/08a–13a purchase-order reference only in UBL; 01.20a seller street/city; 01.21a seller VAT id, payment-means text, exemption reason; 03.01a buyer trading name; 03.06a city/post code swapped; 03.07a seller identifiers and payee legal registration id.

Mapping decisions worth knowing: UBL \`PartyIdentification/ID[@schemeID='SEPA']\` is BT-90 (creditor id), not BT-29; CII \`BasisQuantity\` is read from the net price with the gross price as fallback (03.07a puts it there); the Factur-X/ZUGFeRD "EN 16931" profile URN is only a profile for CII.
`;
writeFileSync(new URL("../docs/BT-COVERAGE.md", import.meta.url), md);
console.log(
  `BT coverage ${covered.size}/${ALL_BT_IDS.length} (${pct} %)${missing.length ? ` missing ${missing.join(", ")}` : ""}`,
);
