/**
 * Generates docs/LICENSES.md from `pnpm licenses list --prod --json` (runtime dependency tree of
 * the whole workspace). CI regenerates it and fails on drift, so a new or unknown licence in the
 * tree is a reviewed change, never a surprise. `--check` exits 1 when the file would change.
 */
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

/** Packages whose package.json says "SEE LICENSE IN …" but whose terms are known and reviewed. */
const KNOWN_UNKNOWN: Record<string, string> = {
  "saxon-js":
    "Saxonica Saxon-JS licence (proprietary; binary redistribution unmodified as part of an application permitted with notice — see NOTICE)",
};
const ACCEPTED = new Set([
  "MIT",
  "ISC",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "0BSD",
  "Apache-2.0",
  "Unlicense",
  "MPL-2.0",
  "MIT or MPL-2.0",
  "(MIT AND Zlib)",
]);

interface Entry {
  name: string;
  versions: string[];
  license: string;
  homepage?: string;
}

const out = fileURLToPath(new URL("../docs/LICENSES.md", import.meta.url));
const raw = execFileSync("pnpm", ["licenses", "list", "--prod", "--json"], {
  cwd: fileURLToPath(new URL("..", import.meta.url)),
  encoding: "utf8",
});
const byLicence = JSON.parse(raw) as Record<string, Entry[]>;

const rows: Array<[string, string, string]> = [];
const problems: string[] = [];
for (const [licence, entries] of Object.entries(byLicence)) {
  for (const e of entries) {
    if (e.name.startsWith("@kontor-mcp/")) continue;
    let lic = licence;
    if (licence === "Unknown") {
      const known = KNOWN_UNKNOWN[e.name];
      if (!known) problems.push(`${e.name}: licence unknown and not reviewed`);
      lic = known ?? "UNKNOWN — review required";
    } else if (!ACCEPTED.has(licence)) {
      problems.push(`${e.name}: licence "${licence}" is not in the accepted list`);
    }
    rows.push([e.name, e.versions.join(", "), lic]);
  }
}
rows.sort((a, b) => a[0].localeCompare(b[0]));

const md = [
  "# Runtime dependency licences",
  "",
  "Generated by `pnpm licenses:build` from `pnpm licenses list --prod --json` over the whole workspace; CI fails when this file drifts from the lockfile (`pnpm licenses:check`). Standards artefacts, fonts and the ICC profile are listed in `NOTICE` and `packages/rules/PROVENANCE.md`.",
  "",
  `${rows.length} packages.`,
  "",
  "| Package | Version(s) | Licence |",
  "|---|---|---|",
  ...rows.map(([n, v, l]) => `| ${n} | ${v} | ${l} |`),
  "",
].join("\n");

if (problems.length) {
  console.error(problems.join("\n"));
  process.exit(2);
}
const check = process.argv.includes("--check");
let previous = "";
try {
  previous = readFileSync(out, "utf8");
} catch {
  /* first run */
}
if (check) {
  if (previous !== md) {
    console.error(
      "docs/LICENSES.md is out of date — run `pnpm licenses:build` and commit the result.",
    );
    process.exit(1);
  }
  console.log(`docs/LICENSES.md up to date (${rows.length} packages).`);
} else {
  writeFileSync(out, md);
  console.log(`wrote docs/LICENSES.md (${rows.length} packages).`);
}
